name: My First Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t vniyigen/ciportfolio .

      - name: List images
        run: docker images

    
            